#!/usr/bin/env bats
#
# BATS Test Suite: DESTRUCTIVE-OPS
# Generated by CLI Testing Specialist
# Target CLI: backup-suite
#

# Setup function (runs before each test)
setup() {
    # Set CLI binary path
    CLI_BINARY="/Users/sanae.abe/projects/backup-suite/target/release/backup-suite"
    BINARY_BASENAME="backup-suite"

    # Export CLI_BINARY for subshell tests (multi-shell compatibility)
    export CLI_BINARY

    # Create temporary directory for test artifacts
    TEST_TEMP_DIR="$(mktemp -d)"
    export TEST_TEMP_DIR

    # Set secure umask
    umask 077
}

# Teardown function (runs after each test)
teardown() {
    # Cleanup temporary directory
    if [[ -n "${TEST_TEMP_DIR:-}" ]] && [[ -d "$TEST_TEMP_DIR" ]]; then
        rm -rf "$TEST_TEMP_DIR"
    fi
}

@test "[destructive-ops] Subcommand 'remove' requires confirmation" {
    # Test ID: destructive-remove-001
    # Tags: confirmation, remove

    # Execute command
    run echo 'n' | "$CLI_BINARY" remove

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "confirm" ]] || [[ "$stderr" =~ "confirm" ]]
}

@test "[destructive-ops] Subcommand 'cleanup' requires confirmation" {
    # Test ID: destructive-cleanup-001
    # Tags: confirmation, cleanup

    # Execute command
    run echo 'n' | "$CLI_BINARY" cleanup

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "confirm" ]] || [[ "$stderr" =~ "confirm" ]]
}

