#!/usr/bin/env bats
#
# BATS Test Suite: DESTRUCTIVE-OPS
# Generated by CLI Testing Specialist
# Modified for backup-suite specific behavior
#

# Setup function (runs before each test)
setup() {
    # Set CLI binary path
    CLI_BINARY="/Users/sanae.abe/projects/backup-suite/target/release/backup-suite"
    BINARY_BASENAME="backup-suite"

    # Export CLI_BINARY for subshell tests (multi-shell compatibility)
    export CLI_BINARY

    # Create temporary directory for test artifacts
    TEST_TEMP_DIR="$(mktemp -d)"
    export TEST_TEMP_DIR

    # Set secure umask
    umask 077

    # CI環境での自動確認を有効化
    export BACKUP_SUITE_YES=true
}

# Teardown function (runs after each test)
teardown() {
    # Cleanup temporary directory
    if [[ -n "${TEST_TEMP_DIR:-}" ]] && [[ -d "$TEST_TEMP_DIR" ]]; then
        rm -rf "$TEST_TEMP_DIR"
    fi

    # Cleanup environment variable
    unset BACKUP_SUITE_YES
}

@test "[destructive-ops] Remove command handles empty target list" {
    # Test ID: destructive-remove-001
    # Tags: confirmation, remove
    # backup-suiteの removeコマンドは登録されたバックアップ対象がない場合、
    # 選択画面でキャンセルされ、exit 0 を返す（エラーではなく正常終了）

    # Execute command
    run "$CLI_BINARY" remove

    # Assert exit code (対象なし・キャンセル時は exit 0)
    [ "$status" -eq 0 ]

    # 警告メッセージを確認
    [[ "$output" =~ "バックアップ対象が登録されていません" ]] || [[ "$stderr" =~ "バックアップ対象が登録されていません" ]]
}

@test "[destructive-ops] Cleanup command with BACKUP_SUITE_YES environment variable" {
    # Test ID: destructive-cleanup-001
    # Tags: confirmation, cleanup
    # BACKUP_SUITE_YES=true が設定されているため、確認プロンプトをスキップ

    # Execute command (dry-runなしで実行)
    run "$CLI_BINARY" cleanup

    # Assert exit code (成功)
    [ "$status" -eq 0 ]

    # CI MODE メッセージを確認
    [[ "$stderr" =~ "[CI MODE]" ]] || true
}
