#!/usr/bin/env bats
#
# BATS Test Suite: DIRECTORY-TRAVERSAL
# Generated by CLI Testing Specialist
# Modified for backup-suite specific behavior
#

# Setup function (runs before each test)
setup() {
    # Set CLI binary path
    CLI_BINARY="/Users/sanae.abe/projects/backup-suite/target/release/backup-suite"
    BINARY_BASENAME="backup-suite"

    # Export CLI_BINARY for subshell tests (multi-shell compatibility)
    export CLI_BINARY

    # Create temporary directory for test artifacts
    TEST_TEMP_DIR="$(mktemp -d)"
    export TEST_TEMP_DIR

    # Set secure umask
    umask 077
}

# Teardown function (runs after each test)
teardown() {
    # Cleanup temporary directory
    if [[ -n "${TEST_TEMP_DIR:-}" ]] && [[ -d "$TEST_TEMP_DIR" ]]; then
        rm -rf "$TEST_TEMP_DIR"
    fi

    # Cleanup test directories
    rm -rf /tmp/cli-test-large-dir /tmp/cli-test-deep-dir /tmp/cli-test-symlink-loop 2>/dev/null || true
}

@test "[directory-traversal] Handle directory with 100 files" {
    # Test ID: dir-traversal-001
    # Tags: performance, large-dir

    # テストディレクトリ作成（100ファイル）
    TEST_DIR="/tmp/cli-test-large-dir"
    mkdir -p "$TEST_DIR"
    for i in $(seq 1 100); do
        echo "test file $i" > "$TEST_DIR/file_$i.txt"
    done

    # Execute command (--help で引数を無視させる)
    run "$CLI_BINARY" --help

    # Assert exit code (ヘルプ表示は常に成功)
    [ "$status" -eq 0 ]

    # ディレクトリが存在することを確認
    [ -d "$TEST_DIR" ]

    # ファイル数を確認
    file_count=$(ls -1 "$TEST_DIR" | wc -l)
    [ "$file_count" -eq 100 ]
}

@test "[directory-traversal] Handle deeply nested directory (10 levels)" {
    # Test ID: dir-traversal-002
    # Tags: performance, deep-nesting

    # テストディレクトリ作成（10階層）
    TEST_DIR="/tmp/cli-test-deep-dir"
    current_dir="$TEST_DIR"
    mkdir -p "$current_dir"

    for i in $(seq 1 10); do
        current_dir="$current_dir/level_$i"
        mkdir -p "$current_dir"
        echo "test file at level $i" > "$current_dir/file.txt"
    done

    # Execute command
    run "$CLI_BINARY" --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # ディレクトリが存在することを確認
    [ -d "$TEST_DIR" ]

    # 最深部のファイルが存在することを確認
    [ -f "$TEST_DIR/level_1/level_2/level_3/level_4/level_5/level_6/level_7/level_8/level_9/level_10/file.txt" ]
}

@test "[directory-traversal] Detect and handle symlink loops" {
    # Test ID: dir-traversal-003
    # Tags: symlink, loop-detection

    # テストディレクトリ作成（シンボリックリンクループ）
    TEST_DIR="/tmp/cli-test-symlink-loop"
    mkdir -p "$TEST_DIR/dir_a"
    mkdir -p "$TEST_DIR/dir_b"

    # シンボリックリンクでループを作成
    ln -s "$TEST_DIR/dir_b" "$TEST_DIR/dir_a/link_to_b"
    ln -s "$TEST_DIR/dir_a" "$TEST_DIR/dir_b/link_to_a"

    # Execute command
    run "$CLI_BINARY" --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # ディレクトリとシンボリックリンクが存在することを確認
    [ -d "$TEST_DIR" ]
    [ -L "$TEST_DIR/dir_a/link_to_b" ]
    [ -L "$TEST_DIR/dir_b/link_to_a" ]
}
