#!/usr/bin/env bats
#
# BATS Test Suite: HELP
# Generated by CLI Testing Specialist
# Target CLI: backup-suite
#

# Setup function (runs before each test)
setup() {
    # Set CLI binary path
    CLI_BINARY="/Users/sanae.abe/projects/backup-suite/target/release/backup-suite"
    BINARY_BASENAME="backup-suite"

    # Export CLI_BINARY for subshell tests (multi-shell compatibility)
    export CLI_BINARY

    # Create temporary directory for test artifacts
    TEST_TEMP_DIR="$(mktemp -d)"
    export TEST_TEMP_DIR

    # Set secure umask
    umask 077
}

# Teardown function (runs after each test)
teardown() {
    # Cleanup temporary directory
    if [[ -n "${TEST_TEMP_DIR:-}" ]] && [[ -d "$TEST_TEMP_DIR" ]]; then
        rm -rf "$TEST_TEMP_DIR"
    fi
}

@test "[help] Display help for subcommand 'add'" {
    # Test ID: help-001
    # Tags: subcommand-help, add

    # Execute command
    run "$CLI_BINARY" add --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'list'" {
    # Test ID: help-002
    # Tags: subcommand-help, list

    # Execute command
    run "$CLI_BINARY" list --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'remove'" {
    # Test ID: help-003
    # Tags: subcommand-help, remove

    # Execute command
    run "$CLI_BINARY" remove --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'clear'" {
    # Test ID: help-004
    # Tags: subcommand-help, clear

    # Execute command
    run "$CLI_BINARY" clear --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'run'" {
    # Test ID: help-005
    # Tags: subcommand-help, run

    # Execute command
    run "$CLI_BINARY" run --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'restore'" {
    # Test ID: help-006
    # Tags: subcommand-help, restore

    # Execute command
    run "$CLI_BINARY" restore --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'cleanup'" {
    # Test ID: help-007
    # Tags: subcommand-help, cleanup

    # Execute command
    run "$CLI_BINARY" cleanup --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'status'" {
    # Test ID: help-008
    # Tags: subcommand-help, status

    # Execute command
    run "$CLI_BINARY" status --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'history'" {
    # Test ID: help-009
    # Tags: subcommand-help, history

    # Execute command
    run "$CLI_BINARY" history --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'dashboard'" {
    # Test ID: help-010
    # Tags: subcommand-help, dashboard

    # Execute command
    run "$CLI_BINARY" dashboard --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'open'" {
    # Test ID: help-011
    # Tags: subcommand-help, open

    # Execute command
    run "$CLI_BINARY" open --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'completion'" {
    # Test ID: help-012
    # Tags: subcommand-help, completion

    # Execute command
    run "$CLI_BINARY" completion --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'schedule'" {
    # Test ID: help-013
    # Tags: subcommand-help, schedule

    # Execute command
    run "$CLI_BINARY" schedule --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'config'" {
    # Test ID: help-014
    # Tags: subcommand-help, config

    # Execute command
    run "$CLI_BINARY" config --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'smart'" {
    # Test ID: help-015
    # Tags: subcommand-help, smart

    # Execute command
    run "$CLI_BINARY" smart --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

