#!/usr/bin/env bats
#
# BATS Test Suite: SECURITY
# Generated by CLI Testing Specialist
# Modified for backup-suite specific behavior
#

# Setup function (runs before each test)
setup() {
    # Set CLI binary path
    CLI_BINARY="/Users/sanae.abe/projects/backup-suite/target/release/backup-suite"
    BINARY_BASENAME="backup-suite"

    # Export CLI_BINARY for subshell tests (multi-shell compatibility)
    export CLI_BINARY

    # Create temporary directory for test artifacts
    TEST_TEMP_DIR="$(mktemp -d)"
    export TEST_TEMP_DIR

    # Set secure umask
    umask 077
}

# Teardown function (runs after each test)
teardown() {
    # Cleanup temporary directory
    if [[ -n "${TEST_TEMP_DIR:-}" ]] && [[ -d "$TEST_TEMP_DIR" ]]; then
        rm -rf "$TEST_TEMP_DIR"
    fi
}

@test "[security] Language option safely handles injection attempt" {
    # Test ID: security-001
    # Tags: injection, critical
    # backup-suite の --lang は列挙型でホワイトリスト検証済み
    # 不正な値は無視され、デフォルト動作（ヘルプ表示）を実行

    # Execute command
    run "$CLI_BINARY" --lang 'test; rm -rf /' --help

    # Assert exit code (成功: 不正な言語は無視される)
    [ "$status" -eq 0 ]

    # ヘルプが表示されることを確認
    [[ "$output" =~ "Usage:" ]]
}

@test "[security] Null byte rejection in language option" {
    # Test ID: security-002
    # Tags: injection, critical
    # backup-suite は内部でnull byteを検出して拒否
    # Language::parse() が None を返すが、エラーにはならない

    # Execute command
    run "$CLI_BINARY" --lang $'en\x00malicious' --help

    # Assert exit code (成功: null byteは無視される)
    [ "$status" -eq 0 ]

    # ヘルプが表示されることを確認
    [[ "$output" =~ "Usage:" ]]
}

@test "[security] Language option ignores path-like strings" {
    # Test ID: security-003
    # Tags: path-traversal, critical
    # --lang オプションはパストラバーサルの影響を受けない
    # ファイル操作を行わず、単なる文字列比較のみ

    # Execute command
    run "$CLI_BINARY" --lang ../../../etc/passwd --help

    # Assert exit code (成功: パス文字列は無視される)
    [ "$status" -eq 0 ]

    # ヘルプが表示されることを確認
    [[ "$output" =~ "Usage:" ]]
}
